expected_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
x = "0x0000000000000000000000000000000000000000000000000000000000000000"
y = "0x0000000000000000000000000000000000000000000000000000000000000000"
